name: Publish snapshot

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: publish-snapshot
  cancel-in-progress: false

jobs:
  publish-snapshot:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/gradle-pipeline.yml
    with:
      publish: true
